general {
    # Welcher Befehl sperrt den Bildschirm?
    lock_cmd = pidof hyprlock || hyprlock

    # Vor dem Suspend (Zuklappen) sperren
    before_sleep_cmd = loginctl lock-session

    # Nach dem Aufwachen Monitor wieder einschalten
    after_sleep_cmd = hyprctl dispatch dpms on
}
