# Preload des Hintergrundbildes (Bleibt unverändert)
preload = ~/Pictures/Wallpapers/wallpaper_black.png

# Neues Block-Format für Version 0.8+
wallpaper {
    monitor = eDP-1
    path = ~/Pictures/Wallpapers/wallpaper_black.png
    fit_mode = cover
}

# Deaktiviert den Hyprland Text unten komplett
splash = false
