general {
    # Sperrt den Bildschirm
    lock_cmd = pidof hyprlock || hyprlock

    # Sperrt den Bildschirm vor dem Suspend (zuklappen)
    before_sleep_cmd = pidof hyprlock || hyprlock

    # Schaltet Monitor wieder ein nach dem aufklappen
    after_sleep_cmd = hyprctl dispatch dpms on
}
