-- [[ Hypland Hauptkonfiguration ]] --
-- Schaltet die gelbe "Autogenerated"-Warnung ab
hl.config({ autogenerated = false })
-- TIPP: Hyprland neu laden ohne Neustart -> hyprctl reload


-- 1. Umgebungsvariablen laden
require("modules.environment-variables")

-- 2. Programme laden
require("modules.my-programs")

-- 3. Monitore einrichten
require("modules.monitors")

-- 4. Eingabegeräte & Gesten laden
require("modules.input")

-- 5. Look & Feel laden
require("modules.theme")

-- 6. Systemeinstellungen laden
require("modules.settings")

-- 7. Fenster-Regeln laden
require("modules.window-rules")

-- 8. Arbeitsbereich-Regeln laden
require("modules.workspace-rules")

-- 9. Tastenkombinationen laden
require("modules.keybinds")

-- 10. Autostart ausführen
require("modules.autostart")
